services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: docker
      PG_USER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: exemplo
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 6611:5432
    